stages:
  - build

build_job:
  stage: build
  image: python:3.10

  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - apt-get update
    - apt-get install -y docker.io

  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest
    - pytest -v
    - docker info
    - docker build -t flask-benchmark .
